export enum AuthRoutes {
  OnBoarding = 'OnBoarding',
  SelectRole = 'SelectRole',
  Login = 'Login',
  BusinessDetails = 'BusinessDetails',
  ResendOtp = 'ResendOtp',
  UserSignUpScreen = 'UserSignUpScreen',
  ForgotPassword = 'ForgotPassword',
  VerificationOtp = 'VerificationOtp',
  NewPassword = 'NewPassword',
  PreviewBusinessDetails = 'PreviewBusinessDetails',
  UserLocationScreen = 'UserLocationScreen',
}

export enum HomeRoutes {
  HomeTabar = 'HomeTabar',
  UpdateProfile = 'UpdateProfile',
  StaffManagement = 'StaffManagement',
  NewBookings = 'NewBookings',
  CompletedBookings = 'CompletedBookings',
  BookingDetails = 'BookingDetails',
  CalendarDetailsScreen = 'CalendarDetailsScreen',
  MessageListingScreen = 'MessageListingScreen',
  ChatScreen = 'ChatScreen',
  StaffActivity = 'StaffActivity',
  StaffUpdates = 'StaffUpdates',
  NotificationsScreen = 'NotificationsScreen',
  ServicesListing = 'ServicesListing',
  NearbySalon = 'NearbySalon',
  TopRatedSalon = 'TopRatedSalon',
  NewToNova = 'NewToNova',
  ShopDescription = 'ShopDescription',
  SpecialtyTreatments = 'SpecialtyTreatments',
  NearbySalonListing = 'NearbySalonListing',
  SearchScreen = 'SearchScreen',
  CheckOutScreen = 'CheckOutScreen',
  OurSpecialistScreen = 'OurSpecialistScreen',
  PaymentScreen = 'PaymentScreen',
  ProceedToCheckout = 'ProceedToCheckout',
  BookingCompleteScreen = 'BookingCompleteScreen',
  LegalInfo = 'LegalInfo',
  AddCard = 'AddCard',
  FullImageView = 'FullImageView',
}
